agcwd_base_alpha: 0.0
agcwd_bright_alpha: 0.0
agcwd_bright_sat_alpha: 0.0
agcwd_bright_sat_beta: 150.0
agcwd_dimmed_alpha: 0.0
agcwd_dimmed_sat_alpha: 0.0
agcwd_dimmed_sat_beta: 0.0
agcwd_highlight_s_thresh: 0
agcwd_highlight_strength: 0.0
agcwd_highlight_v_thresh: 0
agcwd_mean_v_high: 0.0
agcwd_mean_v_low: 0.0
agcwd_neutral_sat_alpha: 0.0
agcwd_neutral_sat_beta: 0.0
agcwd_p95_v_thresh: 0.0
agcwd_sat_median_ksize: 0
agcwd_sat_morph_ksize: 0
agcwd_sat_ratio_thresh: 0.0
brush_size: 8
clahe_clip_limit: 5.05
clahe_tile_size: 10
debug_logging: true
edge_kernel_size: 13
enable_adapt_gamma: true
enable_edge_detection: true
enable_fisheye_undistortion: false
enable_morph_cleanup: true
enable_pre_blur: true
enable_robot_mask: false
fisheye_calibration_file: ''
input_image_topic: /camera/csi_image_2/compressed
jpeg_quality: 10
lane_dilate_size: 20
lut_confidence_lane: 0.0
lut_confidence_road: 0.0
lut_confidence_sidewalk: 0.0
lut_dir: ''
lut_filename: color_lut.npy
morph_kernel_size: 55
output_mask_topic: /segmentation/color_mask/compressed
pre_blur_ksize: 9
pre_blur_sigma: 0.0
publish_undistorted: true
robot_mask_x1: 400
robot_mask_x2: 530
robot_mask_y1: 430
robot_mask_y2: 480
roi_height_ratio: 0.3
smoothing_sigma: 14.0
undistort_balance: 0.0
undistort_scale: 1.0
undistorted_compressed_topic: /qcar2/csi/undistorted/image/compressed
undistorted_jpeg_quality: 50
use_sim_time: false
