agcwd_base_alpha: 0.25
agcwd_bright_alpha: 0.7
agcwd_bright_sat_alpha: 2.0
agcwd_bright_sat_beta: 15.0
agcwd_dimmed_alpha: 0.85
agcwd_dimmed_sat_alpha: 1.5
agcwd_dimmed_sat_beta: 10.0
agcwd_highlight_s_thresh: 80
agcwd_highlight_strength: 0.45
agcwd_highlight_v_thresh: 240
agcwd_mean_v_high: 130.0
agcwd_mean_v_low: 110.0
agcwd_neutral_sat_alpha: 1.4
agcwd_neutral_sat_beta: 5.0
agcwd_p95_v_thresh: 240.0
agcwd_sat_median_ksize: 5
agcwd_sat_morph_ksize: 5
agcwd_sat_ratio_thresh: 0.02
bright_thresh: 90
canny_aperture: 3
canny_debug_topic: /segmentation/canny_debug/compressed
canny_threshold1: 30
canny_threshold2: 250
clahe_clip_limit: 5.05
clahe_tile_size: 30
contrast_thresh: 70
dark_thresh: 300
debug_logging: true
edge_close_iter: 2
edge_close_size: 7
edge_dilate_iter: 2
edge_dilate_size: 8
enable_adapt_gamma: false
enable_component_filter: true
enable_fisheye_undistortion: false
enable_morph_cleanup: false
enable_orientation_filter: true
enable_pre_blur: true
enable_robot_mask: false
fisheye_calibration_file: ''
input_image_topic: /camera/color_image/compressed
jpeg_quality: 10
max_vertical_angle_deg: 25.0
min_component_area: 0
min_component_width: 12
min_edge_pixels: 60
morph_close_iter: 2
morph_kernel_size: 5
morph_open_iter: 1
output_mask_topic: /segmentation/color_mask/compressed
pre_blur_ksize: 9
pre_blur_sigma: 0.0
publish_undistorted: true
robot_mask_x1: 400
robot_mask_x2: 530
robot_mask_y1: 430
robot_mask_y2: 480
roi_height_ratio: 0.3
sample_offset_px: 5
undistort_balance: 0.0
undistort_scale: 1.0
undistorted_compressed_topic: /qcar2/csi/undistorted/image/compressed
undistorted_jpeg_quality: 80
use_black_white_edge_filter: true
use_sim_time: false
vertical_reject_deg: 25.0
